name: Playwright DDT Login Tests
on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ vars.URL_PRODUCCION }} 

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      # ✅ ESTA ES LA SOLUCIÓN: La acción oficial instala todo con permisos correctos
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Ejecutar pruebas de Login DDT
        # Usamos npx aquí porque la acción anterior ya arregló los permisos
        run: npx playwright test --reporter=html

      - name: Subir Reporte HTML
        uses: actions/upload-artifact@v4
        if: always() 

        # ultimo intento
        with:
          name: reporte-playwright
          path: playwright-report/
          retention-days: 7
