name: Playwright DDT Login Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Esto le permite ejecutar la prueba manualmente desde la web

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Instalar navegadores Playwright
        run: npx playwright install --with-deps

      - name: Ejecutar pruebas de Login DDT
        # Agregamos el reporter HTML para la Fase de Reportes
        run: npx playwright test login_ddt.spec.js --reporter=html
        env:
          # ✅ Aquí forzamos que use la variable URL_PRODUCCION de sus Settings
          URL_AMBIENTE: ${{ vars.URL_PRODUCCION }}

      # ✅ PASO NUEVO: Guardar el reporte para verlo después
      - name: Subir Reporte HTML
        uses: actions/upload-artifact@v4
        if: always() # Se ejecuta aunque la prueba falle
        with:
          name: reporte-playwright
          path: playwright-report/
          retention-days: 7
