name: Playwright DDT Login Tests
on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ vars.URL_PRODUCCION }} 

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      # ✅ PASO CRÍTICO: Forzamos permisos de ejecución en los binarios
      - name: Dar permisos de ejecución
        run: chmod +x ./node_modules/.bin/playwright

      - name: Install Playwright Browsers
        # Usamos la ruta directa que acabamos de autorizar
        run: ./node_modules/.bin/playwright install --with-deps chromium

      - name: Ejecutar pruebas de Login DDT
        run: npx playwright test --reporter=html

      - name: Subir Reporte HTML
        uses: actions/upload-artifact@v4
        if: always() 
        with:
          name: reporte-playwright
          path: playwright-report/
          retention-days: 7
